apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongo-backup
spec:
  schedule: "* */24 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongo-backup
              image: premd/mongo-logical-backup-engine:alpha
              env:
                - name: MongoID
                  value: "<MongoId>"
                - name: ALICLOUD_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: mongo-ali-keys
                      key: ALICLOUD_ACCESS_KEY
                - name: ALICLOUD_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: mongo-ali-keys
                      key: ALICLOUD_SECRET_KEY
          restartPolicy: OnFailure
